-- ════════════════════════════════════════════════════════════════════════
-- Base schema (RECONSTRUCTED)  —  DRAFT FOR REVIEW, NOT YET APPLIED
-- ════════════════════════════════════════════════════════════════════════
--
-- WHY THIS FILE EXISTS
--   `main` shipped without a `supabase/` directory, so the original base schema
--   (teams / matches / tournament + register_team / verify_admin_code) was never
--   tracked in the repo — it lived only in the previous owner's Supabase project.
--   The three migrations dated 2026-04-06 / 2026-05-22 are INCREMENTAL: they
--   ALTER/extend these tables and call verify_admin_code, so they assume this base
--   already exists. This file reconstructs that base so a fresh project (the one
--   we own) can be built from migrations alone.
--
-- CONFIDENCE — please review before applying:
--   • Table columns / types / FKs / defaults — HIGH. Derived from
--     src/lib/database.types.ts, minus the columns added by the later migrations
--     (matches.wave, tournament.table_count) and the unique indexes added by the
--     bulk-registration migration (teams code/name).
--   • RLS permissive on teams/matches/tournament — INFERRED. The app reads AND
--     writes these tables directly with the public anon key (admin panel actions +
--     player score reporting), so anon needs full access. Matches the existing
--     "house style". Qualification-critical hardening is applied only to
--     tiebreak_decisions (see the 2026-04-06 migration / issue #18).
--   • Function BODIES (register_team, verify_admin_code) + admin-passphrase
--     storage — LOW / not reconstructable from types. Defined below as a CLEAN
--     mechanism for the new project. Byte-for-byte parity with the old project is
--     NOT required — the frontend only depends on the signatures.
--
-- Column types worth double-checking against the old project:
--   • matches.scheduled_time — modeled as text (free-form "HH:MM" from the admin
--     input). The old column may have been `time` / `timestamptz`.
--   • matches.confirmed_by — modeled as text, no FK (the generated types list no
--     relationship for it, unlike reported_by which is a uuid FK to teams).
-- ════════════════════════════════════════════════════════════════════════

grant usage on schema public to anon, authenticated;

-- ─── teams ──────────────────────────────────────────────────────────────
create table if not exists public.teams (
  id uuid primary key default gen_random_uuid(),
  code text not null,
  name text not null,
  player1 text,
  player2 text,
  wins integer not null default 0,
  losses integer not null default 0,
  checked_in boolean not null default false,
  created_at timestamptz not null default now()
);

-- ─── matches ────────────────────────────────────────────────────────────
-- NOTE: `wave` is intentionally absent here — added by
-- 20260522161000_add_table_capacity_wave_scheduling.sql.
create table if not exists public.matches (
  id uuid primary key default gen_random_uuid(),
  round integer not null,
  team1_id uuid not null references public.teams(id) on delete cascade,
  team2_id uuid not null references public.teams(id) on delete cascade,
  table_number integer,
  scheduled_time text,
  winner_id uuid references public.teams(id) on delete set null,
  loser_id uuid references public.teams(id) on delete set null,
  score_team1 integer,
  score_team2 integer,
  reported_by uuid references public.teams(id) on delete set null,
  confirmed boolean not null default false,
  confirmed_by text,
  created_at timestamptz not null default now()
);

create index if not exists matches_round_idx on public.matches (round);

-- ─── tournament (single row) ────────────────────────────────────────────
-- NOTE: `table_count` is intentionally absent here — added by
-- 20260522161000_add_table_capacity_wave_scheduling.sql.
create table if not exists public.tournament (
  id bigint generated by default as identity primary key,
  current_round integer not null default 0,
  total_rounds integer not null default 7,
  status text not null default 'not_started'
);

-- ─── app_config (admin passphrase store) ────────────────────────────────
-- Single-row config holding the admin passphrase. RLS is enabled with NO
-- policies and NO grants to anon/authenticated, so the public key can never read
-- it; only the SECURITY DEFINER functions below can. Set the real passphrase
-- out-of-band (do NOT commit it):
--   update public.app_config set admin_code = '<your-passphrase>' where id = 1;
create table if not exists public.app_config (
  id integer primary key default 1,
  admin_code text not null default 'CHANGE_ME',
  constraint app_config_singleton check (id = 1)
);

insert into public.app_config (id, admin_code)
values (1, 'CHANGE_ME')
on conflict (id) do nothing;

alter table public.app_config enable row level security;
-- (no policies, no grants → unreadable/unwritable via the public keys)

-- ─── verify_admin_code ──────────────────────────────────────────────────
-- True when `code` matches the stored admin passphrase. SECURITY DEFINER so it
-- can read app_config despite RLS. Called by the admin passphrase gate and by the
-- admin-only RPCs (bulk_register_teams, set_tiebreak_decision).
create or replace function public.verify_admin_code(code text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  return exists (select 1 from public.app_config where admin_code = code);
end;
$$;

grant execute on function public.verify_admin_code(text) to anon, authenticated;

-- ─── register_team ──────────────────────────────────────────────────────
-- Original public self-signup. Retained only so the bulk-registration migration
-- can REVOKE it (public signup is removed in the rebrand). Generates a 6-char
-- ABC123 code and inserts a team.
create or replace function public.register_team(team_name text)
returns table (id uuid, code text, name text)
language plpgsql
security definer
set search_path = public
as $$
declare
  new_code text;
  attempts integer := 0;
begin
  loop
    attempts := attempts + 1;
    new_code :=
      chr(65 + floor(random() * 26)::integer) ||
      chr(65 + floor(random() * 26)::integer) ||
      chr(65 + floor(random() * 26)::integer) ||
      lpad(floor(random() * 1000)::integer::text, 3, '0');
    exit when not exists (select 1 from public.teams t where t.code = new_code);
    if attempts >= 200 then
      raise exception 'CODE_GENERATION_FAILED';
    end if;
  end loop;

  return query
    insert into public.teams as t (name, code)
    values (btrim(team_name), new_code)
    returning t.id, t.code::text, t.name::text;
end;
$$;

grant execute on function public.register_team(text) to anon, authenticated;

-- ─── RLS: teams / matches / tournament (permissive, existing house style) ─
alter table public.teams enable row level security;
drop policy if exists "teams_public_all" on public.teams;
create policy "teams_public_all" on public.teams for all using (true) with check (true);

alter table public.matches enable row level security;
drop policy if exists "matches_public_all" on public.matches;
create policy "matches_public_all" on public.matches for all using (true) with check (true);

alter table public.tournament enable row level security;
drop policy if exists "tournament_public_all" on public.tournament;
create policy "tournament_public_all" on public.tournament for all using (true) with check (true);

grant select, insert, update, delete on public.teams to anon, authenticated;
grant select, insert, update, delete on public.matches to anon, authenticated;
grant select, insert, update, delete on public.tournament to anon, authenticated;
